### ISSUE TITLE
Boxes are not readable

### ISSUE THREAD

**Issue by liam-ngy** [t9md/atom-smalls#3]

**Comment by liam-ngy** [comment]
Hey,

unfortunately the background of the boxes are transparent.
![screen shot 2016-04-20 at 15 33 58](https://cloud.githubusercontent.com/assets/8395044/14676358/66166d7e-070d-11e6-88d3-f53c3f405e50.jpg)

**Comment by t9md** [comment]
I only checked with default color theme.
You can customize it by your own  `style.less`. Check README.md
Thanks

**Comment by mybuddymichael** [comment]
If anyone figures out how to get the configuration to show a background color, I'd love to hear it. I just cannot get an opaque background to show.

**Comment by mybuddymichael** [comment]
Figured it out, I needed to add an additional selector, specifically `atom-text-editor`:

```
atom-text-editor, atom-text-editor::shadow {
  .smalls-label {
    background-color: @app-background-color;
  }
}
```

instead of just

```
atom-text-editor::shadow {
  .smalls-label {
    background-color: @app-background-color;
  }
}
```
